### PR TITLE
feat: personalized notes feed without int firebase reads

### PR DESCRIPTION
**Pull request by DrCheddar**
YEEEEEEEEEEEEEEEEEE FINALLY HOLY CRAP THIS WAS SO MUCH ALGORITHM GRIND HOLY
Notes feed is now individually personalized, first load on the notes feed might take longer but refreshes should be fast
This is my feed, compare it to yours - 
image
Implements #264 , #304

### CODE REVIEW

**Review by picklepower24 — CHANGES_REQUESTED** [review]
image
no worky

**Comment by DrCheddar** [comment]
image
Feed on second account, different grade different subjects

**Review by picklepower24 — APPROVED** [review]
I won't pretend to understand "THE ALGORITHM", but gj!

**Review by allenapplehead — APPROVED** [review]
Algorithm OP. Looks good

**Pull request merged**
